CREATE TABLE MAJESTIC
( 
GlobalRank	INT NOT NULL,
TldRank	INT NOT NULL,
Domain	VARCHAR(80) NOT NULL,
TLD	VARCHAR(30),
RefSubNets	INT,
RefIPs	INT,
IDN_Domain	VARCHAR(80),
IDN_TLD	VARCHAR(30),
PrevGlobalRank	INT,
PrevTldRank	INT,
PrevRefSubNets	INT,
PrevRefIPs INT,
PRIMARY KEY (Domain)
);

CREATE TABLE MAJESTIC_INDEX1
( 
GlobalRank	INT NOT NULL,
TldRank	INT NOT NULL,
Domain	VARCHAR(80) NOT NULL,
TLD	VARCHAR(30),
RefSubNets	INT,
RefIPs	INT,
IDN_Domain	VARCHAR(80),
IDN_TLD	VARCHAR(30),
PrevGlobalRank	INT,
PrevTldRank	INT,
PrevRefSubNets	INT,
PrevRefIPs INT,
PRIMARY KEY (Domain)
);

CREATE INDEX PIndex1
 ON MAJESTIC_INDEX1 (TLD);
 
CREATE TABLE MAJESTIC_INDEX2
( 
GlobalRank	INT NOT NULL,
TldRank	INT NOT NULL,
Domain	VARCHAR(80) NOT NULL,
TLD	VARCHAR(30),
RefSubNets	INT,
RefIPs	INT,
IDN_Domain	VARCHAR(80),
IDN_TLD	VARCHAR(30),
PrevGlobalRank	INT,
PrevTldRank	INT,
PrevRefSubNets	INT,
PrevRefIPs INT,
PRIMARY KEY (Domain)
);

CREATE INDEX PIndex2
 ON MAJESTIC_INDEX2 (RefSubNets); 

CREATE TABLE MAJESTIC_INDEX3
( 
GlobalRank	INT NOT NULL,
TldRank	INT NOT NULL,
Domain	VARCHAR(80) NOT NULL,
TLD	VARCHAR(30),
RefSubNets	INT,
RefIPs	INT,
IDN_Domain	VARCHAR(80),
IDN_TLD	VARCHAR(30),
PrevGlobalRank	INT,
PrevTldRank	INT,
PrevRefSubNets	INT,
PrevRefIPs INT,
PRIMARY KEY (Domain)
);

CREATE INDEX PIndex3
 ON MAJESTIC_INDEX3 (TLD,RefIPs); 
 
